// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDN-MTr6dS2cb-mvXYgez7vyoEtJRBfjhw',
    appId: '1:949137189579:web:ce39a1f5b22a12509a494e',
    messagingSenderId: '949137189579',
    projectId: 'smart-clothing-advisor-2026',
    authDomain: 'smart-clothing-advisor-2026.firebaseapp.com',
    storageBucket: 'smart-clothing-advisor-2026.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAXsBBY8tiyp5OBqdyfVd0kcXerfeo4K4Q',
    appId: '1:949137189579:android:91c1371a48257fd29a494e',
    messagingSenderId: '949137189579',
    projectId: 'smart-clothing-advisor-2026',
    storageBucket: 'smart-clothing-advisor-2026.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnpT7iXZIplz9fycLyRHiMsgYszFnje00',
    appId: '1:949137189579:ios:842e47f6a2ddd5399a494e',
    messagingSenderId: '949137189579',
    projectId: 'smart-clothing-advisor-2026',
    storageBucket: 'smart-clothing-advisor-2026.firebasestorage.app',
    iosBundleId: 'com.example.pfeSmartClothing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnpT7iXZIplz9fycLyRHiMsgYszFnje00',
    appId: '1:949137189579:ios:842e47f6a2ddd5399a494e',
    messagingSenderId: '949137189579',
    projectId: 'smart-clothing-advisor-2026',
    storageBucket: 'smart-clothing-advisor-2026.firebasestorage.app',
    iosBundleId: 'com.example.pfeSmartClothing',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDN-MTr6dS2cb-mvXYgez7vyoEtJRBfjhw',
    appId: '1:949137189579:web:691d094d740922219a494e',
    messagingSenderId: '949137189579',
    projectId: 'smart-clothing-advisor-2026',
    authDomain: 'smart-clothing-advisor-2026.firebaseapp.com',
    storageBucket: 'smart-clothing-advisor-2026.firebasestorage.app',
  );
}
